stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: touch new
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: alpine
      pushRemote: true
      registry: index.docker.io
timeout: 60
